package com.abdo.adf.storeshop.model.eo;

import com.abdo.adf.storeshop.model.util.ModelHelper;

import java.math.BigDecimal;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 13 04:45:12 EEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EducationalLevelImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(EducationalLevelImpl obj) {
                return obj.getId();
            }

            public void put(EducationalLevelImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        Name {
            public Object get(EducationalLevelImpl obj) {
                return obj.getName();
            }

            public void put(EducationalLevelImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Description {
            public Object get(EducationalLevelImpl obj) {
                return obj.getDescription();
            }

            public void put(EducationalLevelImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Groups {
            public Object get(EducationalLevelImpl obj) {
                return obj.getGroups();
            }

            public void put(EducationalLevelImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EducationalSubject {
            public Object get(EducationalLevelImpl obj) {
                return obj.getEducationalSubject();
            }

            public void put(EducationalLevelImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(EducationalLevelImpl object);

        public abstract void put(EducationalLevelImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int GROUPS = AttributesEnum.Groups.index();
    public static final int EDUCATIONALSUBJECT = AttributesEnum.EducationalSubject.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EducationalLevelImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.abdo.adf.storeshop.model.eo.EducationalLevel");
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String)getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getGroups() {
        return (RowIterator)getAttributeInternal(GROUPS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEducationalSubject() {
        return (RowIterator)getAttributeInternal(EDUCATIONALSUBJECT);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }

    protected synchronized void doDML(int operation, TransactionEvent e) {
       if(operation==DML_INSERT){
           try {
               setId(getNextId());
           } catch (SQLException f) {
               f.printStackTrace();
           }
       }
       super.doDML(operation, e);
    }
    
    private Number getNextId() throws SQLException {
       PreparedStatement ps = null;
       ResultSet rs = null;
       Number result=null ;
       try {
           String sql="SELECT nvl(max(C.ID),0)+1 from EDUCATIONAL_LEVEL C ";
           ps = getDBTransaction().createPreparedStatement(sql, 0);
           rs = ps.executeQuery();
           if (rs.next()) {
               return new Number(rs.getString(1));
           }
           return result;
       } catch (Exception e) {
           e.printStackTrace();
       } finally {
           rs.close();
           ps.close();
       }
       return result;
    }
}
