package com.abdo.adf.storeshop.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 06 20:47:54 EEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BillSaleDetailsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BillSaleDetailsViewImpl() {
    }
}
