package com.abdo.adf.storeshop.model.vo.ro;


import com.abdo.adf.storeshop.model.vo.ro.common.productsRoReport;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaManager;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 06 23:14:02 EEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class productsRoReportImpl extends ViewObjectImpl implements productsRoReport {
    /**
     * This is the default constructor (do not remove).
     */
    public productsRoReportImpl() {
    }

    /**
     * Returns the variable value for productParam.
     * @return variable value for productParam
     */
    public Number getproductParam() {
        return (Number)ensureVariableManager().getVariableValue("productParam");
    }

    /**
     * Sets <code>value</code> for variable productParam.
     * @param value value to bind as productParam
     */
    public void setproductParam(Number value) {
        ensureVariableManager().setVariableValue("productParam", value);
    }
    
    public Row getAllAmountProduct(Number productId) {
        ViewCriteriaManager vcm = getViewCriteriaManager();
        ViewCriteria vc = vcm.getViewCriteria("getByProductIdCriteria");
        applyViewCriteria(vc);
        setproductParam(productId);
        executeQuery();
        if(first()!=null){
            Row firstRow = first();
            return firstRow;
        }
       return null;
    }
    
    public void getAlltList() {
        ViewCriteriaManager vcm = getViewCriteriaManager();
        ViewCriteria vc = vcm.getViewCriteria("getAllListCriteria");
        applyViewCriteria(vc);
        executeQuery();
    }
    
}
