package com.abdo.adf.storeshop.model.vo.ro;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 08 03:14:11 EEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class productsRoExImpl extends productsRoReportImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public productsRoExImpl() {
    }
}
