package com.abdo.adf.storeshop.model.vo.ro.common;

import oracle.jbo.ViewObject;
import oracle.jbo.Row;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 06 23:30:48 EEST 2019
// ---------------------------------------------------------------------
public interface productsRoReport extends ViewObject {
    Row getAllAmountProduct(oracle.jbo.domain.Number productId);

    void getAlltList();
}
