package com.abdo.adf.storeshop.model.vo.ro.client;


import com.abdo.adf.storeshop.model.vo.ro.common.productsRoReport;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 06 23:30:49 EEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class productsRoReportClient extends ViewUsageImpl implements productsRoReport {
    /**
     * This is the default constructor (do not remove).
     */
    public productsRoReportClient() {
    }

    public Row getAllAmountProduct(oracle.jbo.domain.Number productId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getAllAmountProduct",new String [] {"oracle.jbo.domain.Number"},new Object[] {productId});
        return (Row)_ret;
    }

    public void getAlltList() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getAlltList",null,null);
        return;
    }
}
